"""empty message

Revision ID: 155e1adaeac
Revises: a969324903
Create Date: 2015-07-11 14:08:31.439091

"""

# revision identifiers, used by Alembic.
revision = '155e1adaeac'
down_revision = 'a969324903'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_snapshot', 'last_update')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_snapshot', sa.Column('last_update', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
