"""empty message

Revision ID: 2fc2e0a7bdc
Revises: 155e1adaeac
Create Date: 2015-07-11 14:09:01.818376

"""

# revision identifiers, used by Alembic.
revision = '2fc2e0a7bdc'
down_revision = '155e1adaeac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_snapshot', sa.Column('last_update', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station_snapshot', 'last_update')
    ### end Alembic commands ###
